@host = http://localhost:8000/api
@name = produtos

### getAll
GET {{host}}/{{name}} HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### getById
GET {{host}}/{{name}}/487 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### store
POST {{host}}/{{name}} HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "id_grupo": "1",
    "id_usuario": "1",
    "valor": "111",
    "descricao": "teste",
    "data_consumo": "2020-10-21"
}

### update
PUT {{host}}/{{name}}/487 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "id": 487,
    "id_grupo": 19,
    "id_usuario": 1,
    "descricao": "teste",
    "valor": "0.03",
    "observacao": "",
    "data_consumo": "2019-12-31T03:00:00.000000Z",
    "updated_at": "2020-01-12T21:36:39.000000Z",
    "created_at": "2019-12-31T03:00:00.000000Z"
}

### delete
DELETE {{host}}/{{name}}/550 HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
