@port = 8000
@host = http://localhost:{{port}}/api
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@name = contas

###
GET {{host}}/{{name}} HTTP/1.1

###
GET {{host}}/{{name}}/15 HTTP/1.1

###
POST {{host}}/{{name}} HTTP/1.1
Content-Type: {{contentType}}

{
    "tipo": "1",
    "titulo": "teste",
    "valor": "520.66",
    "forma_pagamento": "outros",
    "mais_informacoes": "teste",
    "id_usuario": "49",
    "id_certificacao": "4606",
    "olha": "teste"
}
