@host = http://localhost:8000/api
@name = produtos
@auth = xxxxxxx

### getAlll
GET {{host}}/{{name}} HTTP/1.1
Authorization: Bearer {{auth}}

### getById
GET {{host}}/{{name}}/150 HTTP/1.1
Authorization: Bearer {{auth}}

### store
POST {{host}}/{{name}} HTTP/1.1
Content-Type: application/json

{
    "id_grupo": "16",
    "id_usuario": "1",
    "valor": "520.66",
    "descricao": "outros",
    "data_consumo": "2020-10-21"
}

### update
PUT {{host}}/{{name}}/1 HTTP/1.1
Content-Type: application/json

{
    "id_grupo": "2",
    "valor": "5.76",
    "descricao": "Pão",
    "observacao": "teste2",
    "data_criacao": "2018-12-31"
}

### delete
DELETE {{host}}/{{name}}/1 HTTP/1.1
