@host = http://localhost:8000/api
@name = users

### login
POST {{host}}/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "sistema3@yes.com",
    "password": "123"
}

### store
POST {{host}}/{{name}} HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "email": "sistema2@yes.com",
    "password": "123",
    "name": "Politano"
}
