@host = http://localhost:8000/api
@name = produtos

### getAll
GET {{host}}/{{name}} HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### getById
GET {{host}}/{{name}}/150 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### store
POST {{host}}/{{name}} HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "id_grupo": "1",
    "id_usuario": "1",
    "valor": "111",
    "descricao": "teste",
    "data_consumo": "2020-10-21"
}

### update
PUT {{host}}/{{name}}/552 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "id_grupo": "2",
    "valor": "222",
    "descricao": "Teste Atualizado",
    "observacao": "obs teste",
    "data_criacao": "2018-12-31"
}

### delete
DELETE {{host}}/{{name}}/552 HTTP/1.1
Authorization: Bearer {{token}}
