@host = http://localhost:8000/api

@contentType = application/json
@createdAt = {{$datetime iso8601}}
@name = users

### login
POST {{host}}/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "felipe10@yes.com",
    "password": "123"
}

### get
GET {{host}}/{{name}}/1 HTTP/1.1

### store
POST {{host}}/{{name}} HTTP/1.1
Content-Type: {{contentType}}
Accept: application/json

{
    "email": "sistema15@yes.com",
    "password": "123",
    "name": "Politano"
}

###
GET {{host}}/factory HTTP/1.1

###
GET {{host}}/notifications HTTP/1.1

###
PUT {{host}}/notifications/1 HTTP/1.1
Content-Type: {{contentType}}

{
    "id": "a02139fc-3319-463c-ba83-2f36d538103d"
}
